Repository kauecdev/crypto-react-app, pull requests merged in 2022-03, with the labels that each got.

#1 Config Project
  .gitignore
  README.md
  README.old.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: configuration

#2 Adicionar configurações e dependências para branch principal
  .gitignore
  README.md
  README.old.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: configuration

#3 002 clean project
  README.md
  README.old.md
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.test.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: configuration

#4 004: logo adicionada no projeto
  src/assets/logo-crypto.png
Labels: enhancement

#5 att: readme
  README.old.md
Labels: documentation

#6 att: readme
  README.old.md
  src/assets/cryptosearchhome.png
Labels: documentation

#7 att: readme
  README.md
Labels: documentation

#9 Sprint 1 - Concluída
  README.md
  README.old.md
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/cryptosearchhome.png
  src/assets/logo-crypto.png
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: sprint
